"use client";

import { X } from "lucide-react";
import type { DecisionSignal } from "@/types/analysis";

const priorityStyles = { high: "bg-[#fff0ed] text-[#a8402d]", medium: "bg-[#fff6df] text-[#9a6b1f]", low: "bg-[#edf5f0] text-[#41745e]" };

export function DecisionSignalDrawer({ signal, onClose }: { signal: DecisionSignal | null; onClose: () => void }) {
  if (!signal) return null;
  return <div className="fixed inset-0 z-50"><button type="button" aria-label="Close signal details" className="absolute inset-0 bg-[#102c22]/35 backdrop-blur-[1px]" onClick={onClose} /><aside role="dialog" aria-modal="true" aria-labelledby="signal-title" className="absolute inset-y-0 right-0 flex w-full max-w-xl flex-col overflow-y-auto bg-[#fbfdfb] shadow-[-18px_0_50px_rgba(13,46,34,0.18)]"><div className="flex items-start justify-between border-b border-[#e1eae5] px-6 py-6 sm:px-8"><div><p className="text-xs font-semibold tracking-[0.14em] text-[#638277]">DECISION SIGNAL #{signal.id}</p><h2 id="signal-title" className="mt-2 text-2xl font-semibold tracking-[-0.04em] text-[#23493b]">{signal.title}</h2></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-[#6c8378] transition hover:bg-[#edf4f0] hover:text-[#23493b]" aria-label="Close"><X className="size-5" aria-hidden="true" /></button></div><div className="flex-1 px-6 py-7 sm:px-8"><div className="grid grid-cols-3 gap-3"><Detail label="Priority" value={signal.priority} className={priorityStyles[signal.priority]} /><Detail label="Confidence" value={`${signal.confidence}%`} /><Detail label="Status" value={signal.status} /></div><DrawerSection title="Business exposure"><div className="flex flex-wrap gap-2">{signal.exposure.map((item) => <span key={item} className="rounded-full bg-[#eaf3ee] px-2.5 py-1 text-xs font-medium text-[#4a7664]">{item}</span>)}</div></DrawerSection><DrawerSection title="Why it matters"><p className="text-sm leading-6 text-[#577168]">{signal.whyItMatters}</p></DrawerSection><DrawerSection title="Evidence"><ul className="space-y-2">{signal.evidence.map((item) => <li key={item} className="flex gap-2 text-sm leading-5 text-[#577168]"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-[#64a287]" />{item}</li>)}</ul></DrawerSection><DrawerSection title="Recommendation"><div className="rounded-xl border border-[#cfe1d7] bg-[#f1f8f4] p-4 text-sm leading-6 text-[#365e4e]">{signal.recommendation}</div></DrawerSection><DrawerSection title="Suggested owner"><p className="text-sm font-medium text-[#365e4e]">{signal.suggestedOwner}</p></DrawerSection></div></aside></div>;
}

function Detail({ label, value, className = "bg-[#eef5f1] text-[#41745e]" }: { label: string; value: string; className?: string }) { return <div className="rounded-xl border border-[#e0ebe5] bg-white p-3"><p className="text-[10px] font-semibold tracking-[0.11em] text-[#90a098]">{label.toUpperCase()}</p><p className={`mt-2 inline-flex rounded-full px-2 py-0.5 text-xs font-semibold capitalize ${className}`}>{value}</p></div>; }
function DrawerSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-7"><h3 className="mb-3 text-sm font-semibold text-[#35584a]">{title}</h3>{children}</section>; }
