import type { ResponseFormatTextJSONSchemaConfig } from "openai/resources/responses/responses";
import {
  ASSESSMENT_CONFIDENCES,
  BUSINESS_EXPOSURE_AREAS,
  BUSINESS_EXPOSURE_LEVELS,
  HEALTH_STATUSES,
  RECOMMENDATIONS,
  SIGNAL_PRIORITIES,
  SIGNAL_STATUSES,
} from "@/types/analysis";

export const ANALYSIS_RESPONSE_FORMAT: ResponseFormatTextJSONSchemaConfig = {
  type: "json_schema",
  name: "sage_analysis_result",
  description: "Evidence-backed executive initiative assessment for the Sage dashboard.",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    required: [
      "source",
      "projectName",
      "analyzedAt",
      "documentCount",
      "healthScore",
      "healthStatus",
      "assessmentConfidence",
      "recommendation",
      "recommendationDetail",
      "summary",
      "signals",
      "businessExposure",
      "nextActions",
    ],
    properties: {
      source: { type: "string", enum: ["live"] },
      projectName: { type: "string", minLength: 1 },
      analyzedAt: { type: "string", minLength: 1 },
      documentCount: { type: "integer", minimum: 1 },
      healthScore: { type: "integer", minimum: 0, maximum: 100 },
      healthStatus: { type: "string", enum: HEALTH_STATUSES },
      assessmentConfidence: { type: "string", enum: ASSESSMENT_CONFIDENCES },
      recommendation: { type: "string", enum: RECOMMENDATIONS },
      recommendationDetail: { type: "string", minLength: 1 },
      summary: {
        type: "array",
        minItems: 3,
        maxItems: 5,
        items: { type: "string", minLength: 1 },
      },
      signals: {
        type: "array",
        minItems: 0,
        maxItems: 5,
        items: {
          type: "object",
          additionalProperties: false,
          required: [
            "id",
            "title",
            "priority",
            "confidence",
            "exposure",
            "status",
            "whyItMatters",
            "evidence",
            "recommendation",
            "suggestedOwner",
          ],
          properties: {
            id: { type: "string", minLength: 1 },
            title: { type: "string", minLength: 1 },
            priority: { type: "string", enum: SIGNAL_PRIORITIES },
            confidence: { type: "integer", minimum: 0, maximum: 100 },
            exposure: {
              type: "array",
              minItems: 1,
              items: { type: "string", enum: BUSINESS_EXPOSURE_AREAS },
            },
            status: { type: "string", enum: SIGNAL_STATUSES },
            whyItMatters: { type: "string", minLength: 1 },
            evidence: {
              type: "array",
              minItems: 1,
              items: { type: "string", minLength: 1 },
            },
            recommendation: { type: "string", minLength: 1 },
            suggestedOwner: { type: "string", minLength: 1 },
          },
        },
      },
      businessExposure: {
        type: "array",
        minItems: 3,
        maxItems: 3,
        items: {
          type: "object",
          additionalProperties: false,
          required: ["area", "level", "detail"],
          properties: {
            area: { type: "string", enum: BUSINESS_EXPOSURE_AREAS },
            level: { type: "string", enum: BUSINESS_EXPOSURE_LEVELS },
            detail: { type: "string", minLength: 1 },
          },
        },
      },
      nextActions: {
        type: "array",
        minItems: 3,
        maxItems: 5,
        items: { type: "string", minLength: 1 },
      },
    },
  },
};
