import type { AnalysisResult } from "@/types/analysis";

export const mockAnalysis: AnalysisResult = {
  source: "mock",
  projectName: "Digital Claims Transformation",
  analyzedAt: "21 July 2026",
  documentCount: 4,
  healthScore: 78,
  healthStatus: "Stable, needs attention",
  assessmentConfidence: "High",
  recommendation: "Proceed with Conditions",
  recommendationDetail: "The initiative is directionally sound, but execution should begin only after the highest-priority governance and delivery gaps are addressed.",
  summary: [
    "The business case and target operating model are well defined, with clear sponsorship from Claims and Operations leadership.",
    "The proposed Q4 launch remains achievable, but the current plan does not include enough time for vendor integration testing.",
    "A formal compliance review gate and a named end-to-end testing owner are required before user acceptance testing begins.",
  ],
  signals: [
    {
      id: "01",
      title: "Missing compliance approval gate",
      priority: "high",
      confidence: 94,
      exposure: ["Regulatory", "Timeline"],
      status: "Open",
      whyItMatters: "Production deployment is planned without a documented compliance sign-off. A late review could delay go-live after the delivery team has already committed resources.",
      evidence: ["Project Charter — delivery milestones", "BRD §4.2 — controls and approvals", "Steering Committee Notes — 15 July"],
      recommendation: "Introduce a mandatory compliance review milestone before UAT and assign an accountable Compliance Lead.",
      suggestedOwner: "Compliance Lead",
    },
    {
      id: "02",
      title: "Vendor integration timeline is compressed",
      priority: "high",
      confidence: 91,
      exposure: ["Timeline", "Financial"],
      status: "Open",
      whyItMatters: "The plan allocates two weeks for a dependency that historically requires four to six. Any slippage would absorb the contingency reserved for user acceptance testing.",
      evidence: ["Integrated Project Plan — workstream 3", "Vendor SOW — test environment readiness", "Meeting Notes — 11 July"],
      recommendation: "Rebaseline the integration plan with the vendor and protect a minimum two-week UAT contingency.",
      suggestedOwner: "Technology Delivery Lead",
    },
    {
      id: "03",
      title: "End-to-end testing ownership is unclear",
      priority: "medium",
      confidence: 87,
      exposure: ["Timeline", "Financial"],
      status: "Open",
      whyItMatters: "Responsibilities are distributed across business and technology teams, but no one is accountable for end-to-end test readiness or defect triage.",
      evidence: ["BRD §6 — testing approach", "RACI draft — version 0.3"],
      recommendation: "Assign a single testing owner with authority to coordinate test data, environments, and defect decisions.",
      suggestedOwner: "Programme Director",
    },
    {
      id: "04",
      title: "Customer communications plan is absent",
      priority: "medium",
      confidence: 82,
      exposure: ["Regulatory"],
      status: "Open",
      whyItMatters: "The operating change affects customer claim-status communications, yet no owner or approval path is present in the rollout plan.",
      evidence: ["Project Charter — change scope", "Change Plan — version 0.2"],
      recommendation: "Add a customer communication workstream and confirm Legal and Brand review requirements.",
      suggestedOwner: "Head of Change",
    },
    {
      id: "05",
      title: "Benefits tracking starts too late",
      priority: "low",
      confidence: 76,
      exposure: ["Financial"],
      status: "Open",
      whyItMatters: "The benefits baseline is scheduled after the first release, limiting the ability to demonstrate whether automation benefits are being realised.",
      evidence: ["Business Case — benefits assumptions", "Project Plan — benefits workstream"],
      recommendation: "Establish the benefits baseline before build completion and review it monthly with the sponsor.",
      suggestedOwner: "PMO Lead",
    },
  ],
  businessExposure: [
    { area: "Regulatory", level: "high", detail: "Compliance sign-off is not embedded in the delivery plan." },
    { area: "Timeline", level: "medium", detail: "Integration and UAT contingency are constrained." },
    { area: "Financial", level: "medium", detail: "Benefits tracking and delivery contingency need protection." },
  ],
  nextActions: [
    "Introduce the compliance review gate before UAT.",
    "Rebaseline the vendor integration timeline.",
    "Assign one accountable end-to-end testing owner.",
    "Confirm the customer communications workstream.",
  ],
};
